spring:
  datasource:
      url: jdbc:postgresql://${DB_URL}:5432/poupacompra
      username: ${DB_USERNAME}
      password: ${DB_PASSWORD}
  jpa:
    open-in-view: false
    show-sql: false
    properties:
       hibernate:
         dialect: org.hibernate.dialect.PostgreSQLDialect