server:
  port: 8182
  servlet:
    context-path: /integracao-poupa-compra
#   tomcat:
#     accesslog:
# # here we say that we want to enable accesslog
#       enabled : false
# # it is important to understand what the options means:
# # 'directory/prefix + suffix + file-date-format' will be
# # the file that tomcat will try to open.
# # /dev/stdout is standard output, so we want tomcat
# # to write to that fd. Then, we need to play with
# # directory, prefix, suffix and file-date-format to match our desired path.
#       directory: /dev
#       prefix: stdout
#       buffered: false
#       suffix:
#       file-date-format:
spring:
  application:
    name: "integracao-poupa-compra"
  main:
    banner-mode: "off"
  datasource:
      url: jdbc:postgresql://${ds.integracao.pc.url}/poupa_compra
      username: ${ds.integracao.pc.user}
      password: ${ds.integracao.pc.password}
      driver-class-name: org.postgresql.Driver
      # name: ds.valhalla.seguros_azul
      # hikari:
      #   pool-name: ${spring.application.name}__postgres__poupacompra
      #   maximum-pool-size: 20
      #   minimum-idle: 5
      #   idle-timeout: 60000
      #   connection-timeout: 5000
      #   max-lifetime: 180000
      #   auto-commit: false
      #   transaction-isolation: TRANSACTION_READ_COMMITTED
      #   connection-test-query: select 1
      
  jpa:
    open-in-view: false
    show-sql: true
    properties:
       hibernate:
         dialect: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    enabled: false
  web:
    resources:
      add-mappings: false
  jackson:
    deserialization:
      fail-on-unknown-properties: true
      fail-on-ignored-properties: true
logging:
  group:
    tomcat: "org.apache.catalina,org.apache.coyote,org.apache.tomcat,org.apache.http"
  level:
    ROOT: INFO
    tomcat: INFO
    sql: INFO
    web: INFO
    "[poupacompra.integracao]": DEBUG
    "[ch.qos.logback]": ERROR
    "[com.amazonaws]": WARN
    "[com.netflix.discovery]": ERROR
    # "[com.zaxxer.hikari]": INFO
    "[com.tngtech.archunit]": ERROR
    "[com.sun]": INFO
    "[io.github.resilience4j]": INFO
    "[io.micrometer]": INFO
    "[io.awspring]": INFO
    "[javax.management.mbeanserver]": INFO
    "[javax.management.remote.rmi]": INFO
    "[javax.xml]": INFO
    "[jdk.event.security]": INFO
    "[org.flywaydb]": INFO
    "[org.jboss]": INFO
    "[org.hibernate]": ERROR
    "[org.mariadb]": INFO
    "[org.postgresql]": INFO
    "[org.springframework.aop]": INFO
    "[org.springframework.beans]": INFO
    "[org.springframework.boot]": INFO
    "[org.springframework.cloud]": INFO
    "[org.springframework.cloud.configuration]": INFO
    "[org.springframework.cloud.context]": INFO
    "[org.springframework.cloud.openfeign]": INFO
    "[org.springframework.cloud.sleuth]": INFO
    "[org.springframework.context]": INFO
    "[org.springframework.core]": INFO
    "[org.springframework.data]": INFO
    "[org.springframework.jdbc]": ERROR
    "[org.springframework.jmx]": ERROR
    "[org.springframework.orm]": INFO
    "[org.springframework.oxm]": INFO
    "[org.springframework.amqp.rabbit]": INFO
    "[org.springframework.scheduling]": INFO
    "[org.springframework.security]": ERROR
    "[org.springframework.test]": INFO
    "[org.springframework.ui]": ERROR
    "[org.springframework.web]": INFO
    "[org.springframework.ws]": INFO
    "[org.springframework.ws.client.MessageTracing.sent]": TRACE
    "[org.springframework.ws.client.MessageTracing.received]": TRACE
    "[_org.springframework.web.servlet]": INFO
    "[reactor.util]": INFO
    "[reactor.core]": INFO
    "[sun.rmi]": ERROR
    "[sun.net]": DEBUG
    "[unknown.jul.logger]": ERROR
---
# spring:
#   config:
#     import: "file:/run/secrets/integracao-poupa-compra.config[.properties]"
#     activate:
#       on-profile: "dev | hmg | prd"
