spring:
  # elasticsearch:
  #    uris: 62.164.217.75:9200
  #    username: elastic
  #    password: didwmz53
  datasource:
      url: jdbc:postgresql://localhost:5432/poupa_compra
      username: postgres
      password: postgresql
